name: Build release binaries

on:
  push:
    tags:
    - "*"
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.18.0'
    - name: Build x86_64
      run: ./build.sh