name: Build release binaries

on:
  push:
    tags:
    - "*"
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.18.0'

    # Install all the dependencies
    - name: Install dependencies
      run: go version


    # Run build of the application
    - name: Build x86_64
      run: ./build.sh